### ISSUE TITLE
split withdrawals into rightsholder / streamer / WR

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/dashboard#167]
expected split:
- rightsholder 75%
- streamer 10%
- WR 15%

The basic split could be defined as follows:

![image](https://user-images.githubusercontent.com/163447/107517567-f5661b80-6bbe-11eb-86e9-0b5559317aad.png)

The split parameters will be set in CollectionPool same for all the movies / RHs. Later on, this should be changeable per waterfall.

## Prerequisites

To make per-payment splits (e.g. transfer revenue cut to PSS) work, the following has to be implemented first:
- keep payment hashes on chain and change claimRevenue contract function to accept payments list #210
- index payments per movie #211

## Scope
- query the list of unprocessed payments from indexer (#211) — use filter by `status` and `region`.
- use new version of claim function (#210) providing the list of payments when calling collecting pool to distribute the revenue
- recover from the possible claim errors (e.g. concurrent claims can lead to failed txs because the payments are already processed etc)
- split itself is implemented as part of #210 

## Roles

gardener: @troggy 50 DAI
worker: @troggy 420 DAI
reviewer: [reviewer] 80 DAI

**Comment by Right2Rebel** [comment]
1. Another ticket needed for Waterfall itself (75%)
2. PSS dependent for streamer, otherwise 80/20 split

**Comment by troggy** [comment]
@mwaa there is no definition/scope in this ticket

**Comment by Olivier7777** [comment]
@Right2Rebel Why don't we keep it simple: 75% for RH. 15% for WR. 10% for a 3rp party partner or collected by WR if none.

**Comment by Right2Rebel** [comment]
@troggy @mwaa  what do you think about above statement from @Olivier7777 

my reservation is that the money is then sitting somewhere and now requires administration. perhaps we could make some intent behind those 10%... as well as PSS it could be used to fund dApps or films or something in this order... question is how to automate this.

1. another solution is to have the 10% go into a pool and based on number of active users for each PSS they split the entire pool ... seems long-winded but could be automated? its collective but how does it reward individual success?

2. another solution is that all PSS must have our javascript integrated in their website, connecting the users plug-in with the javascript, communicating and confirming its a PSS and initiating the 10% payout - otherwise the 25% goes to WR - or 15% / 10% which goes to a pool for other intents and purposes 

3. also I assume our plug-in could have verified PSS lists so any stream from the PSS list initiates a 10% cut... probably not as secure as 2.

**Comment by troggy** [comment]
@Right2Rebel my only comment is that it is not "simple" to implement. We have no infrastructure so far to have per-payment splits, which will be needed to implement "10% for a 3rp party partner or collected by WR if none."

We need to implement it first, for that this task needs proper definition of what is needed to be done on a technical side.
That's why I suggested to start with a simpler split (see my diagram in the ticket itself)

**Comment by Olivier7777** [comment]
@troggy Kosta, do you mean that having a test like "there is / there is not a PSS" before the split process itself results complicated?

**Comment by Right2Rebel** [comment]
We do the split 75/25... when it comes to the 25 it may be split again, but that depends on the extent of our PSS campaign and then with the 75 it comes down to the RH...

**Comment by Right2Rebel** [comment]
Cost of CC charge = 29 cents per payment (+% of amount which is covered by WR)
75% of 29 cents = 21.75 cents
Charge of 21 cents off the top to start with 
Review every three-to-six months RH share of CC payment (as some users may bulk pay) and reduce when possible

**Comment by Olivier7777** [comment]
@Right2Rebel Alan, isn't it 30c$ instead of 29c$?

**Comment by Right2Rebel** [comment]
Yes you are correct. So 22 cents off the top.

**Comment by troggy** [comment]
via #216
